export interface City {
    name: string;
    department: string;
}

export const COLOMBIA_CITIES: City[] = [
    { name: 'Leticia', department: 'Amazonas' },
    { name: 'Puerto Nariño', department: 'Amazonas' },
    { name: 'Medellín', department: 'Antioquia' },
    { name: 'Bello', department: 'Antioquia' },
    { name: 'Itagüí', department: 'Antioquia' },
    { name: 'Envigado', department: 'Antioquia' },
    { name: 'Apartadó', department: 'Antioquia' },
    { name: 'Rionegro', department: 'Antioquia' },
    { name: 'Turbo', department: 'Antioquia' },
    { name: 'Caucasia', department: 'Antioquia' },
    { name: 'Arauca', department: 'Arauca' },
    { name: 'Tame', department: 'Arauca' },
    { name: 'Saravena', department: 'Arauca' },
    { name: 'Barranquilla', department: 'Atlántico' },
    { name: 'Soledad', department: 'Atlántico' },
    { name: 'Malambo', department: 'Atlántico' },
    { name: 'Sabanagrande', department: 'Atlántico' },
    { name: 'Bogotá D.C.', department: 'Bogotá D.C.' },
    { name: 'Cartagena', department: 'Bolívar' },
    { name: 'Magangué', department: 'Bolívar' },
    { name: 'Turbaco', department: 'Bolívar' },
    { name: 'Tunja', department: 'Boyacá' },
    { name: 'Sogamoso', department: 'Boyacá' },
    { name: 'Duitama', department: 'Boyacá' },
    { name: 'Chiquinquirá', department: 'Boyacá' },
    { name: 'Manizales', department: 'Caldas' },
    { name: 'La Dorada', department: 'Caldas' },
    { name: 'Villamaría', department: 'Caldas' },
    { name: 'Florencia', department: 'Caquetá' },
    { name: 'San Vicente del Caguán', department: 'Caquetá' },
    { name: 'Yopal', department: 'Casanare' },
    { name: 'Aguazul', department: 'Casanare' },
    { name: 'Popayán', department: 'Cauca' },
    { name: 'Santander de Quilichao', department: 'Cauca' },
    { name: 'Valledupar', department: 'Cesar' },
    { name: 'Aguachica', department: 'Cesar' },
    { name: 'Quibdó', department: 'Chocó' },
    { name: 'Montería', department: 'Córdoba' },
    { name: 'Lorica', department: 'Córdoba' },
    { name: 'Sahagún', department: 'Córdoba' },
    { name: 'Cereté', department: 'Córdoba' },
    { name: 'Soacha', department: 'Cundinamarca' },
    { name: 'Girardot', department: 'Cundinamarca' },
    { name: 'Facatativá', department: 'Cundinamarca' },
    { name: 'Zipaquirá', department: 'Cundinamarca' },
    { name: 'Chía', department: 'Cundinamarca' },
    { name: 'Mosquera', department: 'Cundinamarca' },
    { name: 'Madrid', department: 'Cundinamarca' },
    { name: 'Funza', department: 'Cundinamarca' },
    { name: 'Cajicá', department: 'Cundinamarca' },
    { name: 'Inírida', department: 'Guainía' },
    { name: 'San José del Guaviare', department: 'Guaviare' },
    { name: 'Neiva', department: 'Huila' },
    { name: 'Pitalito', department: 'Huila' },
    { name: 'Garzón', department: 'Huila' },
    { name: 'Riohacha', department: 'La Guajira' },
    { name: 'Maicao', department: 'La Guajira' },
    { name: 'Santa Marta', department: 'Magdalena' },
    { name: 'Ciénaga', department: 'Magdalena' },
    { name: 'Fundación', department: 'Magdalena' },
    { name: 'Villavicencio', department: 'Meta' },
    { name: 'Acacías', department: 'Meta' },
    { name: 'Pasto', department: 'Nariño' },
    { name: 'Tumaco', department: 'Nariño' },
    { name: 'Ipiales', department: 'Nariño' },
    { name: 'Cúcuta', department: 'Norte de Santander' },
    { name: 'Ocaña', department: 'Norte de Santander' },
    { name: 'Villa del Rosario', department: 'Norte de Santander' },
    { name: 'Los Patios', department: 'Norte de Santander' },
    { name: 'Pamplona', department: 'Norte de Santander' },
    { name: 'Mocoa', department: 'Putumayo' },
    { name: 'Puerto Asís', department: 'Putumayo' },
    { name: 'Armenia', department: 'Quindío' },
    { name: 'Calarcá', department: 'Quindío' },
    { name: 'Pereira', department: 'Risaralda' },
    { name: 'Dosquebradas', department: 'Risaralda' },
    { name: 'Santa Rosa de Cabal', department: 'Risaralda' },
    { name: 'San Andrés', department: 'San Andrés y Providencia' },
    { name: 'Bucaramanga', department: 'Santander' },
    { name: 'Floridablanca', department: 'Santander' },
    { name: 'Barrancabermeja', department: 'Santander' },
    { name: 'Girón', department: 'Santander' },
    { name: 'Piedecuesta', department: 'Santander' },
    { name: 'Sincelejo', department: 'Sucre' },
    { name: 'Corozal', department: 'Sucre' },
    { name: 'Ibagué', department: 'Tolima' },
    { name: 'El Espinal', department: 'Tolima' },
    { name: 'Melgar', department: 'Tolima' },
    { name: 'Cali', department: 'Valle del Cauca' },
    { name: 'Buenaventura', department: 'Valle del Cauca' },
    { name: 'Palmira', department: 'Valle del Cauca' },
    { name: 'Tuluá', department: 'Valle del Cauca' },
    { name: 'Yumbo', department: 'Valle del Cauca' },
    { name: 'Cartago', department: 'Valle del Cauca' },
    { name: 'Jamundí', department: 'Valle del Cauca' },
    { name: 'Buga', department: 'Valle del Cauca' },
    { name: 'Mitú', department: 'Vaupés' },
    { name: 'Puerto Carreño', department: 'Vichada' }
];
